"""Tests for the rendering helpers (:func:`kroki.is_svg`, :func:`kroki.bytes_to_image`)
and for the argument validation of :func:`kroki.diagram_image_bytes`.

All of these run offline. ``is_svg`` and ``bytes_to_image`` are pure functions of
their bytes, and the ``@validate_literal`` rejection path raises before any HTTP
request is attempted -- which the "rejected before any request" test below pins
down explicitly, by making the request itself an error.
"""

import base64

import pytest
from IPython.display import SVG, Image

import kroki
from kroki import bytes_to_image, diagram_image_bytes, is_svg

# A real (if tiny) 1x1 PNG, so that the non-SVG cases exercise a payload that
# IPython's Image would actually accept rather than an arbitrary byte string.
PNG_BYTES = base64.b64decode(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVR4nGP4"
    "//8/AAX+Av4N70a4AAAAAElFTkSuQmCC"
)

SVG_PAYLOADS = {
    "bare": b'<svg xmlns="http://www.w3.org/2000/svg"></svg>',
    "xml_declaration": (
        b'<?xml version="1.0" encoding="UTF-8"?>\n'
        b'<svg xmlns="http://www.w3.org/2000/svg"/>'
    ),
    "doctype": b'<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN">\n<svg/>',
    "xml_declaration_then_comment": (
        b'<?xml version="1.0"?>\n<!-- generated by kroki -->\n<svg/>'
    ),
}

NON_SVG_PAYLOADS = {
    "png": PNG_BYTES,
    "empty": b"",
    "html": b"<html><body></body></html>",
    "plain_text": b"Bob->Alice : Hello!",
}


@pytest.mark.parametrize("payload", SVG_PAYLOADS.values(), ids=list(SVG_PAYLOADS))
def test_is_svg_recognises_svg(payload):
    assert is_svg(payload) is True


@pytest.mark.parametrize(
    "payload", NON_SVG_PAYLOADS.values(), ids=list(NON_SVG_PAYLOADS)
)
def test_is_svg_rejects_non_svg(payload):
    assert is_svg(payload) is False


def test_bytes_to_image_dispatches_on_content():
    """SVG bytes become a displayable ``SVG``; anything else becomes an ``Image``."""
    assert isinstance(bytes_to_image(SVG_PAYLOADS["bare"]), SVG)
    assert isinstance(bytes_to_image(PNG_BYTES), Image)


@pytest.mark.parametrize(
    "kwargs, offending_argument",
    [
        ({"diagram_type": "not-a-diagram-type"}, "diagram_type"),
        ({"output_format": "not-an-output-format"}, "output_format"),
    ],
)
def test_diagram_image_bytes_rejects_invalid_literals(kwargs, offending_argument):
    with pytest.raises(ValueError) as excinfo:
        diagram_image_bytes("Bob->Alice : Hello!", **kwargs)
    assert offending_argument in str(excinfo.value)


def _patch_requests(monkeypatch, get):
    """Swap the ``requests`` name in :mod:`kroki`'s own namespace.

    Narrower than patching ``requests.get`` itself, which would be visible to every
    other user of the module for the duration of the test.
    """
    fake = type("_Requests", (), {"get": staticmethod(get)})
    monkeypatch.setattr(kroki, "requests", fake)


def test_invalid_arguments_are_rejected_before_any_request(monkeypatch):
    """Validation must be pre-flight: an invalid argument never reaches the network."""

    def fail_if_called(url):
        raise AssertionError(f"diagram_image_bytes issued an HTTP request to {url}")

    _patch_requests(monkeypatch, fail_if_called)

    with pytest.raises(ValueError):
        diagram_image_bytes("Bob->Alice : Hello!", diagram_type="not-a-diagram-type")


def test_every_advertised_literal_passes_validation(monkeypatch):
    """Guard against the validator becoming over-strict.

    Every key of ``output_formats`` must be an accepted ``diagram_type`` and every
    value an accepted ``output_format``. (This checks each value individually, not
    that a given pair is one kroki.io actually supports -- the ``Literal`` types are
    built from the flattened sets, so they cannot express the pairing.)
    """
    sentinel = b"<svg/>"

    class _Ok:
        status_code = 200
        content = sentinel

    _patch_requests(monkeypatch, lambda url: _Ok())

    for diagram_type, formats in kroki.output_formats.items():
        for output_format in formats:
            assert (
                diagram_image_bytes(
                    "Bob->Alice : Hello!",
                    diagram_type=diagram_type,
                    output_format=output_format,
                )
                == sentinel
            )


def test_non_200_response_raises(monkeypatch):
    """A failed request must surface as an error, not as bogus image bytes."""

    class _NotFound:
        status_code = 404
        content = b"no such diagram"

    _patch_requests(monkeypatch, lambda url: _NotFound())

    with pytest.raises(RuntimeError, match="404"):
        diagram_image_bytes("Bob->Alice : Hello!")
